# Generated by Django 5.2.16 on 2026-07-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
